### ISSUE TITLE
Acces cache from production environment

### ISSUE THREAD

**Issue by JohnnyEvo** [schmittjoh/JMSDiExtraBundle#188]
Hi,

JMSDiExtra doesn't access to cache from production's environment only (no problem in development). The problem is present in online's (pre)production's development (testing on heroku and platform.sh) : 

    Warning: require_once(/tmp/build_80c8af6ae6a26860e4005894cda1684b/app/cache/prod/jms_diextra/proxies/XXX-Controller-XXXController.php): failed to open stream: No such file or directory in /app/app/cache/prod/jms_diextra/controller_injectors/XXXBundleControllerXXXController.php line 13
    E_COMPILE_ERROR: require_once(): Failed opening required '/tmp/build_80c8af6ae6a26860e4005894cda1684b/app/cache/prod/jms_diextra/proxies/XXXBundle-Controller-XXXController.php' (include_path='/app/vendor/phpunit/php-text-template:/app/vendor/phpunit/phpunit-mock-objects:/app/vendor/phpunit/php-timer:/app/vendor/phpunit/php-file-iterator:/app/vendor/phpunit/php-code-coverage:/app/vendor/phpunit/phpunit:/app/vendor/symfony/yaml:.:/app/.heroku/php/lib/php') in /app/app/cache/prod/jms_diextra/controller_injectors/XXXBundleControllerXXXController.php line 13

And local production's development : 

    Warning: unlink(/Users/xxx/xxx/xxx/xxx/app/cache/prod/annotations/54bccb2dc8e409.23806260ZLC6J5): No such file or directory in /Users/xxx/xxx/xxx/xxx/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php line 214
    Warning: unlink(/Users/xxx/xxx/xxx/xxx/app/cache/prod/annotations/54bccb3a76a0e2.39941614K5BS1a): No such file or directory in /Users/xxx/xxx/xxx/xxx/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php line 214

Same issue with Symfony 2.5.* and Symfony 2.6.*.

The JMSDiExtra's version is 1.5.0.

Problem maybe in relation with https://github.com/symfony/symfony/pull/12784

**Comment by prof-web-coding** [comment]
I'm getting a similar error in the test environment:
`PHP Warning:  Uncaught require_once(/[...]/var/cache/test/jms_diextra/doctrine/EntityManager_57a4d8f42d3bb.php): failed to open stream: No such file or directory`
Looking into the directory I can see that a file EntityManager_57a4d90632186.php is created....
This only happens on Linux, running it on Windows everything works fine.
Any ideas?

**Comment by buffcode** [comment]
Running jms/di-extra 1.8.1 the metadata still contains absolute paths. These can differ when moving from deployment/staging to production. Symfony already has patches for this situation:
- https://github.com/symfony/symfony/pull/19687
- https://github.com/symfony/symfony/pull/12784
- https://github.com/symfony/symfony/pull/10894
