### ISSUE TITLE
conflict with services and addClassesToCompile()

### ISSUE THREAD

**Issue by Ma27** [schmittjoh/JMSDiExtraBundle#193]
when I try to compile a class which is a service handled by the DiExtraBundle, I get the following error:

```
Cannot redeclare class
```

This might be caused since this bundle tries to find the service in the configured directory, but the class cache will be loaded before that, so the compiled class is already imported.

Is it possible to fix this issue??

**Comment by wodka** [comment]
I guess you have spelled the class different than the file name.

If it is exactly the same (including upper/lower case) then please provide the exact filenames and class definition
