### ISSUE TITLE
symfony 2.7 support?

### ISSUE THREAD

**Issue by gondo** [schmittjoh/JMSDiExtraBundle#198]
after updating to symfony 2.7 this bundle is throwing lots of deprecated warning
any plans to make this compatible with s2.7 s2.8 and eventually s3.* ?

**Comment by schmittjoh** [comment]
We do support Symfony 2.7 - and there is also an issue/PR to provide forward compatibility with 3.0. Closing this one here.

**Comment by gondo** [comment]
can you provide issue/PR number please?
"We do support Symfony 2.7" doesnt seems to be the case. ad mentioned above, running composer update cause lots of Deprecated warnings

**Comment by stof** [comment]
@gondo a deprecation warning does not mean it does not work. It means it will stop working in 3.0.

**Comment by gondo** [comment]
@stof if its polluting console output a `composer update` is part of continuous integration and if it cause different behavior then before, than yes it does mean that something ll break

**Comment by stof** [comment]
different behavior ?
