### ISSUE TITLE
symfony 3 support

### ISSUE THREAD

**Issue by Ma27** [schmittjoh/JMSDiExtraBundle#224]
could you please tag a new release that supports sf 3.0?

**Comment by Ma27** [comment]
hmm, there are other bundles with other build issues :/

**Comment by grafity** [comment]
I just hope the new version.

Thanks...

**Comment by Ma27** [comment]
It'll take some time since the JMSAopBundle and the JMSSecurityExtraBundle must be fixed first and I don't get any answer of @schmittjoh  :/

**Comment by awildeep** [comment]
:( I was really hoping this bundle would be working in 3.x.   I guess I go back to manually defining my services for now.

**Comment by Ma27** [comment]
I'll wait a little bit since it is currently weekend, but if the time comes when migrating my applications, I'll also remove this stuff here unless a new major release of this bundle comes.

**Comment by pinouf** [comment]
+1 need -)

**Comment by remialvado** [comment]
+1

**Comment by tubssp** [comment]
+1

**Comment by thomask** [comment]
+1

**Comment by kachkaev** [comment]
+1

**Comment by khasinski** [comment]
+1

**Comment by whyte624** [comment]
:+1:

**Comment by bassrock** [comment]
:+1:

**Comment by e-doceo** [comment]
+1

**Comment by Ma27** [comment]
the PR just waits until the JMSSecurityExtraBundle is fixed (they depend on each other)

**Comment by amustaine** [comment]
+1

**Comment by SulivanDotEu** [comment]
+1

**Comment by Catalin-Ionut** [comment]
+1

**Comment by sblondeau** [comment]
+1

**Comment by Jean85** [comment]
Ping @Ener-Getick ;)

**Comment by Ener-Getick** [comment]
@Jean85 I'm waiting to merge two other PRs and then I'll create ``1.6.0-BETA``.

**Comment by Jean85** [comment]
@Ener-Getick did you mean `1.7.0-BETA`? 1.6 is already tagged here...

**Comment by Ener-Getick** [comment]
@Jean85 Yeah sorry of course that's ``1.7.0-BETA``.

**Comment by Ener-Getick** [comment]
[``1.7.0-BETA``](https://github.com/schmittjoh/JMSDiExtraBundle/releases/tag/1.7.0-BETA) is released ! :-)

**Comment by Ener-Getick** [comment]
I released [``1.7.0``](https://github.com/schmittjoh/JMSDiExtraBundle/releases/tag/1.7.0)
