### ISSUE TITLE
DEPRECATED ResourceInterface::isFresh()

### ISSUE THREAD

**Issue by yalg** [schmittjoh/JMSDiExtraBundle#226]
Deprecated function : The class "JMS\DiExtraBundle\Config\ServiceFilesResource" is performing resource checking through ResourceInterface::isFresh(), which is deprecated since 2.8 and will be removed in 3.0

https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#config

I thing this is just the namespace to change, but i don't know if there is other dependencies

**Comment by Ma27** [comment]
see #224
