### ISSUE TITLE
How can use decorates property in a service definition?

### ISSUE THREAD

**Issue by rafrsr** [schmittjoh/JMSDiExtraBundle#230]
I trying to use something like

@Service(decorates="foo")

like described [here](http://symfony.com/doc/2.8/components/dependency_injection/advanced.html#decorating-services)

This property is missing, exist another way to do this with JMSDiExtraBundle?

right now the only way that I see is using the services.yml

> The property `deprecated` added in symfony 2.8, should also be available

**Comment by wodka** [comment]
there is a pull request for both properties - soon this can be done

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/schmittjoh/JMSDiExtraBundle/pull/237
