### ISSUE TITLE
Change AfterSetup Annotation to simply call method

### ISSUE THREAD

**Issue by wodka** [schmittjoh/JMSDiExtraBundle#239]
remove the usage of initMethod and add it to the methodCalls array

-> found in https://github.com/schmittjoh/JMSDiExtraBundle/pull/238#discussion_r52848161

**Comment by Ener-Getick** [comment]
:+1:

**Comment by wodka** [comment]
the AfterSetup annotation is not working at all right now, why not improve it to be invoked depending on the created service (https://github.com/schmittjoh/JMSDiExtraBundle/pull/238)

```php
use JMS\DiExtraBundle\Annotation as DI;

/**
 * @DI\Service("first.service")
 * @DI\Service("second.service")
 */
class MultiService
{
    /**
     * @DI\InjectParams({
     *     "foo" = @DI\Inject("%foo%")
     * })
     *
     * @DI\AfterSetup(service="first.service")
     */
    public function initFirst($foo)
    {}


    /**
     * @DI\InjectParams({
     *     "foo" = @DI\Inject("%foo%")
     * })
     *
     * @DI\AfterSetup(service="second.service")
     */
    public function initSecond($bar)
    {}
}
```

**Comment by Ener-Getick** [comment]
In fact it works but only for the classes not defined as services (like the controllers). 

And why not but it should be an array of services as we will soon support multiple services on a single class thanks to you :-)

**Comment by Ener-Getick** [comment]
In fact ``InjectParams`` does the same job as ``AfterSetup`` so we would maybe just deprecate it.

**Comment by wodka** [comment]
mhmm - I cannot find how this is supposed to work on controllers, the neither definition nor the DefinitionDecorator object have the function to setup initMethods - how can they then inject anything?

perhaps also just add a new parameter services to injectParams -> I'll do that now

**Comment by Ener-Getick** [comment]
@wodka Yeah you're right, it doesn't work at all...

**Comment by wodka** [comment]
do you think we should fix the AfterSetup to simply call a method? I would add it then as well

It can be useful because it does not require params for the function

**Comment by Ener-Getick** [comment]
@wodka ``InjectParams`` doesn't require to define params so I do not see any advantages to keep ``AfterSetup``.
But ``InjectParams`` is maybe not well named, do you have any idea of a more descriptive name ?

**Comment by wodka** [comment]
it does require params -> else it will simply skip the method https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/Metadata/Driver/AnnotationDriver.php#L178

```php
if (!$params) {
    continue;
}
```

but perhaps we could rename it to something like "Call" to be more in line with symfony

```
/**
 * @DI\Call(services={"only.for.this"})
 */
```

**Comment by Ener-Getick** [comment]
Ah right, then we should probably remove this check.
And yeah, ``Call`` seems better to me.

**Comment by wodka** [comment]
I would then move the InjectParams code to a new class Call that implements the MetadataInterface (just like: https://github.com/wodka/SonataAdminBundle/blob/jms-annotation/Annotation/Admin.php)

this will in the long run clean up the AnnotationDriver (no more instanceof checks!!)

**Comment by Ener-Getick** [comment]
@wodka I don't think that's a good practice, annotations are only meant to contain data not logic.

I opened https://github.com/schmittjoh/JMSDiExtraBundle/pull/240, can you take a look at it please?

**Comment by wodka** [comment]
having many instanceof checks is not good practice either :(

perhaps to return the AnnotationProcessor for this specific Annotation? It also should be easy for other Projects to create Custom Annotations.

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/schmittjoh/JMSDiExtraBundle/pull/243
