### ISSUE TITLE
FormType annotation relies on deprecated AbstractType->getName() method

### ISSUE THREAD

**Issue by rejsmont** [schmittjoh/JMSDiExtraBundle#251]
As of Symfony 3.0 form types are referenced by full class name, not by aliases, so dependency on getName() method should be optional or removed.

**Comment by Ener-Getick** [comment]
Does https://github.com/schmittjoh/JMSDiExtraBundle/pull/252 fix your issue ?

**Comment by rejsmont** [comment]
Totally!

**Comment by Ener-Getick** [comment]
#252 is merged ;-)
