### ISSUE TITLE
[RFC] Support for Symfony 2.8/3 Autowiring

### ISSUE THREAD

**Issue by lemoinem** [schmittjoh/JMSDiExtraBundle#253]
Since Symfony 2.8, the DI component supports a built-in autowiring system for the dependencies (for the constructor argument).

This autowiring system is based on arguments types (instead of argument names).
It means adding the support for two new configurations (autowire and autowiringType).

Would you be interested by a PR adding the support for these features in JMS Di Extra?

**Comment by ksom** [comment]
👍

**Comment by Ener-Getick** [comment]
Of course :+1:
