### ISSUE TITLE
All services are broken (dev-master)

### ISSUE THREAD

**Issue by adadgio** [schmittjoh/JMSDiExtraBundle#266]
I just did a composer update yesterday, and I use jms/di-extra-bundle from dev- master.

On cache clear, ALL services defined with @DI\Service are broken (Symfony\...\ServiceNotFoundException).

I've not beeing changin any service definition for over a year. Any chance something bad happened recently on this repository ?

**Comment by goetas** [comment]
Please check which other dependencies have been updated comparing your `composer.lock` file

**Comment by alecszaharia** [comment]
For me it stopped working after I updated the sonata-project/admin-bundle to 3.11.0..
It works fine with  sonata-project/admin-bundle 3.10.3

**Comment by gagaXD** [comment]
Same here, since I upgrade sonata-project/admin-dundle to 3.11.0, all my services are broken.

**Comment by Nightbr** [comment]
Same here... I tried to use `"jms/di-extra-bundle": "^1.7"` but the problem still persist...

My workaround so far: `"sonata-project/admin-bundle": "3.10.*"`

**Comment by anboo** [comment]
Now it is dangerous to use this bundle.

**Comment by Nightbr** [comment]
Hey @anboo, you mean JmsDIExtraBundle or SonataAdminBundle is dangerous to use ?

**Comment by adadgio** [comment]
Ok so this is not a JMS DI Extra Bundle issue, i think this should be closed.

**Comment by adadgio** [comment]
Here are the fixes !! (both references are actually the same issue, first one is quicker to read.

https://github.com/sonata-project/SonataAdminBundle/issues/4349#issuecomment-282680817

https://github.com/sonata-project/SonataAdminBundle/issues/4292#issuecomment-275454008

In short, add this to your `jsm_di_extra` config: 

```yaml
jms_di_extra:
   annotation_patterns:
      - "JMS\\DiExtraBundle\\Annotation"
```
