### ISSUE TITLE
Problem with LoggerDataCollector

### ISSUE THREAD

**Issue by Sozialarchiv** [schmittjoh/JMSDiExtraBundle#277]
With Symfony 3.3 there is a problem:

See: https://github.com/symfony/symfony/issues/22952

**Comment by chosroes** [comment]
I've made a PR #276

**Comment by Sozialarchiv** [comment]
Thank you

**Comment by Wirone** [comment]
@GuilhemN this should be closed then?

**Comment by GuilhemN** [comment]
Indeed, thanks.
