### ISSUE TITLE
Notice: Undefined property: JMS\DiExtraBundle\Metadata\ClassMetadata::$decoration_inner_ame' in Metadata/MetadataConverter.php:91 

### ISSUE THREAD

**Issue by igst** [schmittjoh/JMSDiExtraBundle#279]
Commit 37db08e24ee9acdf4588ff5574f9dca0391a89dd broke the MetadataConverter.

$decoration_inner_ame should be $decoration_inner_name? :-)

**Comment by GuilhemN** [comment]
Indeed, fixed in https://github.com/schmittjoh/JMSDiExtraBundle/commit/52072e64cf9226d336dd32cc4407c83200954d15, thanks !
