### ISSUE TITLE
addClassesToCompile deprecated

### ISSUE THREAD

**Issue by MisatoTremor** [schmittjoh/JMSDiExtraBundle#281]
Used in JMSDiExtraBundle/DependencyInjection/JMSDiExtraExtension.php:74

BC compatible fix would be to enclose with if (\PHP_VERSION_ID < 70000) { ... }

**Comment by Sozialarchiv** [comment]
Would a solution like the following possible?

https://github.com/schmittjoh/JMSI18nRoutingBundle/blob/master/DependencyInjection/JMSI18nRoutingExtension.php#L49

```
if (PHP_VERSION_ID < 70000) {
  $this->addClassesToCompile(array(
    $container->getDefinition('jms_i18n_routing.router')->getClass(),
  ));
}
```


https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/DependencyInjection/JMSDiExtraExtension.php#L74

**Comment by noofaq** [comment]
+1

**Comment by Sozialarchiv** [comment]
https://github.com/schmittjoh/JMSDiExtraBundle/pull/278
