### ISSUE TITLE
addClassesToCompile() is deprecated since Symfony version 3.3, to be removed in 4.0

### ISSUE THREAD

**Issue by nemalion** [schmittjoh/JMSDiExtraBundle#290]
Hello,

Currently on Symfony 3.3.9, I just want to point out this small depreciation that is located in this file:

`jms/di-extra-bundle/DependencyInjection/JMSDiExtraExtension.php:75`

See you :)

**Comment by greg0ire** [comment]
There already is a condition depending on php 7, so you must be using php 5 I guess? Maybe this isn't the right condition. Do you know since when this is deprecated?

**Comment by nemalion** [comment]
I'm running Symfony under php 7.0 and the condition is correct. I just realized that I run with version 1.8.2 of JMSDiExtraBundle. I installed it with Composer without specifying a specific version, so I have the version with the last tag by default.
I specified the dev-master version in my composer.json, the Symfony profiler is satisfied.
Thank you for your reply.

**Comment by GuilhemN** [comment]
Done https://github.com/schmittjoh/JMSDiExtraBundle/releases/tag/1.9.0 :)
