### ISSUE TITLE
Symfony 3.4

### ISSUE THREAD

**Issue by pdias** [schmittjoh/JMSDiExtraBundle#296]
After upgrade to Symfony 3.4 i have this warnings:

> User Deprecated: The "jms_di_extra.metadata.metadata_factory" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

> User Deprecated: The "jms_di_extra.metadata_driver" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

Thanks,

Paulo Dias

**Comment by LailaMai** [comment]
Hello @pdias @GuilhemN ,
I have the same deprecation message since my update to 3.4 : 

> User Deprecated: The "jms_di_extra.metadata_driver" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

This Issues has been closed without any apparent reason or solution, can you please tell me how to resolve it ?

**Comment by GuilhemN** [comment]
This was solved in https://github.com/schmittjoh/JMSDiExtraBundle/pull/299, it just isn't released yet. Will do.

**Comment by LailaMai** [comment]
Actually I removed these lines from config.yml: 

> jms_di_extra:
>     automatic_controller_injections:
>         properties:
>             request: "@request"
>             router: "@router"
>         method_calls:
>             setRouter: ["@router"]

As weird as it looks, the deprecation message disappeared and everything seems to work fine like before!
