### ISSUE TITLE
Doctrine orm service must be true by default

### ISSUE THREAD

**Issue by pdias** [schmittjoh/JMSDiExtraBundle#298]
After update to SF3.4 i have this warning (**if doctrine_integration is set to true in config, default is true**):

> User Deprecated: The "doctrine.orm.default_entity_manager" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

This warning is caused by the JMSDIExtraBundle proxy replacing the Doctrine service.

JMSDIExtraBundle, does not properly preserve the service visibility when overwriting the service.

Thanks,

Paulo Dias

**Comment by ajtis** [comment]
@pdias please create new rel/tag.

**Comment by slawomirkania** [comment]
@pdias like above, please create tag
