### ISSUE TITLE
Annotations not working when using PHP through FastCGI

### ISSUE THREAD

**Issue by valepu** [schmittjoh/JMSDiExtraBundle#300]
Hello,
I'm trying to use PHP with FastCGI rather than Apache handler but whenever I start using FastCGI dependency Injection annotations stop working and I receive an error saying that a service can't be found whenever i try to go into a page with a Controller that uses one of the annotated services

I know it sounds weird, but if i switch back to Apache handler everything works fine. Other annotations (such as those from Doctrine, or Symfony Routes) work fine in both cases.

It's worth mentioning that i'm running PHP 7.1 with Apache 2.4 on Windows 10, I'm using symfony 3.4 and the dev-master version of this bundle

**Comment by valepu** [comment]
This is the configuration i use for FastCGI

```
<IfModule fcgid_module>
	FcgidInitialEnv PATH "C:/xampp/php"
	FcgidInitialEnv SystemRoot "C:/Windows"
	FcgidInitialEnv SystemDrive "C:"
	FcgidInitialEnv TEMP "C:/xampp/tmp"
	FcgidInitialEnv TMP "C:/xampp/tmp"
	FcgidInitialEnv windir "C:/windows"
	FcgidIOTimeout 64
	FcgidConnectTimeout 16
	FcgidMaxRequestsPerProcess 1000 
	FcgidMaxProcesses 3
	FcgidMaxRequestLen 8131072
	# Location php.ini:
	FcgidInitialEnv PHPRC "C:/xampp/php"
	FcgidInitialEnv PHP_FCGI_MAX_REQUESTS 1000

	<Files ~ "\.php$">
		Options Indexes FollowSymLinks ExecCGI 
		AddHandler fcgid-script .php
		FcgidWrapper "C:/xampp/php/php-cgi.exe" .php
	</Files>
</IfModule>
```

While this is for Apache handler

```
#
# PHP-Module setup
#
LoadFile "C:/xampp/php/php7ts.dll"
LoadFile "C:/xampp/php/libpq.dll"
LoadModule php7_module "C:/xampp/php/php7apache2_4.dll"

<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>

<IfModule php7_module>
    PHPINIDir "C:/xampp/php"
</IfModule>
```

**Comment by valepu** [comment]
I noticed, right after posting the configuration, that i set up the PATH field incorrectly. Adding windows folders to the PATH fixed the issue

`FcgidInitialEnv PATH "C:/xampp/php;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;"`

**Comment by greg0ire** [comment]
Congrats on fixing this! Can you please close the issue?
