### ISSUE TITLE
Compatible with Symfony4 require

### ISSUE THREAD

**Issue by gam6itko** [schmittjoh/JMSDiExtraBundle#301]
User Deprecated: The "jms_di_extra.metadata.metadata_factory" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0.

User Deprecated: The "jms_di_extra.metadata_driver" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0.

**Comment by GuilhemN** [comment]
This is already fixed, see https://github.com/schmittjoh/JMSDiExtraBundle/commit/71fac349dfdfa85a7ebcc3b95a9cd82f4de59052.

**Comment by stedekay** [comment]
I upgraded this bundle to version 1.9.1, so this fix is already included. But when I type `php bin/console debug:container jms_di_extra.metadata_driver` it says that the aliased service `jms_di_extra.metadata.driver.configured_controller_injections` is still private. Even when I remove my config the now aliased service `jms_di_extra.metadata.driver.annotation_driver` is also private.

Any ideas?
