### ISSUE TITLE
Unrecognized options

### ISSUE THREAD

**Issue by andreybolonin** [schmittjoh/JMSDiExtraBundle#302]
After upgrade from symfony 3.1 to 3.4:

``Unrecognized options "title, title_logo, options, templates" under "jms_di_extra" ``

Any ideas?

``"name": "jms/di-extra-bundle",
            "version": "1.9.1",``

``Exception trace:
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php:299
 Symfony\Component\Config\Definition\BaseNode->normalize() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php:33
 Symfony\Component\Config\Definition\Processor->process() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php:50
 Symfony\Component\Config\Definition\Processor->processConfiguration() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Extension/Extension.php:96
 Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at /Users/andreybolonin/www/froomba/vendor/sonata-project/admin-bundle/src/DependencyInjection/SonataAdminExtension.php:319
 Sonata\AdminBundle\DependencyInjection\SonataAdminExtension->prepend() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:43
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:634
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/andreybolonin/www/froomba/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/andreybolonin/www/froomba/bin/console:29
``

**Comment by Saracevas** [comment]
Do you still remember how you fixed this? Having exactly the same problem with Sonata Admin Bundle and JMSDIExtraBundle...
