### ISSUE TITLE
[JMS\DiExtraBundle\Exception\RuntimeException] on shared server

### ISSUE THREAD

**Issue by mrothauer** [schmittjoh/JMSDiExtraBundle#84]
hi,

i am trying to run symfony2 on a shared server.

php-version as apache module: 5.3
php-version as CLI: 5.4

the problem is, that any app/console-call, e.g.
php app/console assets:install web --prod=staging

fails with the following error message:

[JMS\DiExtraBundle\Exception\RuntimeException]  
 Command "/bin/grep --extended-regexp --directories=recurse --devices=skip --files-with-matches --with-filename --color=never --include=_.php '._' '/www/htdocs/staging/src/Tet/PageBundle/Resources/translations' '/www/htdocs/staging/vendor/symfony/symfony/src/Symfony/Component/Form/Resources/translations' '/www/htdocs/staging/vendor/symfony/symfony/src/Symfony/Component/Validator/Resources/translations'" exited with non-successful status code "127".

thanks,
mario

**Comment by tsiory** [comment]
Can you explain how you resolved the problem please? Thanks!

**Comment by mrothauer** [comment]
Sorry, it's too long ago (7 years).

**Comment by tsiory** [comment]
But can you tell me if the issue was in the server or in the code? because that's works on our test server but not on prod server, thanks in advance!

**Comment by mrothauer** [comment]
> problem solved, it had to do with Chroot on our shared server.

As far as I remember, we did not have to change the code.

**Comment by tsiory** [comment]
Okay, thanks for your help!
